#!/bin/sh

echo ">>>>>>default config copy OK"
cp buildroot_defconfig .config

echo ">>>>>>buildroot project run $1"
make -C /home/buildroot-2023.02 O=/home/buildroot-output BR2_EXTERNAL=../buildroot-external-s5000c $1
